// <auto-generated />
namespace Librarian.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PKNamesCorrected : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PKNamesCorrected));
        
        string IMigrationMetadata.Id
        {
            get { return "202103131505304_PKNamesCorrected"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
